env: local
is_debug: true
listen:
  bind_ip: localhost
  port: 1234
  timeout: 15s
  idle_timeout: 60s
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres
  max_attempts: 3